"""
Specification Search Script for Paper 216541-V1
"The Management of Aid and Conflict in Africa" by Jacob Moscona
Published in AEJ: Policy

CRITICAL NOTE:
This replication package does NOT include the processed analysis datasets.
The Data/Analysis directory is empty. The analysis requires intermediate datasets
that are generated by Stata scripts using spatial operations (shp2dta, geoinpoly)
that cannot be replicated in Python without extensive GIS preprocessing.

REQUIRED BUT MISSING DATASETS:
- wb_project_with_conflict_F.dta (main analysis dataset)
- wb_project_grid_cell_F.dta (intermediate data)
- conflict_panel_grid_F.dta (conflict data by grid cell)
- grid_cells_year.dta (panel structure)
- project_level_vam_formerge_*.dta (leader value-added data)

WHAT WE CAN ACCESS:
- Raw World Bank project data (CSV)
- Raw ACLED conflict data (Excel)
- TTL (Team leader) CV data (DTA)
- Project database (DTA)
- 1-degree grid structure (CSV)
"""

import pandas as pd
import numpy as np
import json
import os
from datetime import datetime

# Define paths
BASE_PATH = "/Users/gabesekeres/Dropbox/Papers/competition_science/agentic_specification_search"
PACKAGE_PATH = f"{BASE_PATH}/data/downloads/extracted/216541-V1/Replication_MACA"
RAW_DATA_PATH = f"{PACKAGE_PATH}/Data/Raw"
OUTPUT_PATH = PACKAGE_PATH

PAPER_ID = "216541-V1"
JOURNAL = "AEJ: Policy"
PAPER_TITLE = "The Management of Aid and Conflict in Africa"

# ============================================================================
# PAPER OVERVIEW FROM ANALYSIS OF DO FILES
# ============================================================================
"""
MAIN HYPOTHESIS:
- Better-managed World Bank aid projects REDUCE conflict in African grid cells
- The treatment variable is `mean_qoutcome` (average project outcome score, 1-6)
- Control for project presence (`any_aid`)

KEY IDENTIFICATION STRATEGY:
1. Panel fixed effects: Grid cell FE + Year FE (or Year x Country FE)
2. Instrumental Variables for project quality using team leader fixed effects
   - Leader dummies as instruments for project score (845 leaders)
   - Uses LIML estimation
3. Additional IV for project presence using aid exposure outside Africa

PRIMARY OUTCOME VARIABLES:
- i_conflict: Any conflict event indicator
- i_violent_conflict: Violent conflict indicator
- i_conflictf: Conflict with fatalities indicator
- i_greater1_d: Multiple conflicts indicator (>1 event)

DATA STRUCTURE:
- Unit: 1-degree grid cells across Africa (~1000+ cells)
- Time: 1995-2014 (20 years)
- N observations: ~40,000+ grid-cell-years

METHODS CLASSIFICATION:
- Primary: Panel Fixed Effects with IV (using leader fixed effects as instruments)
- Also includes: OLS with FE, IV/LIML estimation

FIXED EFFECTS USED:
- Grid cell FE (ID)
- Year FE (yr)
- Year x Country FE (yr#ccode) in some specifications
- Sector FE (sect1d_*) as controls

CLUSTERING:
- Clustered at grid cell level (ID) - baseline
- Clustered at country level (ccode) - robustness

KEY CONTROL VARIABLES:
- any_aid: Aid project presence indicator
- sect1d_*: 75 sector dummies
- Geographic controls: agsuit (agricultural suitability), petrol, diamond, split
"""

# ============================================================================
# ATTEMPT TO LOAD AVAILABLE DATA
# ============================================================================

def load_available_data():
    """Load whatever raw data is accessible."""
    data_info = {}

    # 1. Load ACLED conflict data
    try:
        acled_path = f"{RAW_DATA_PATH}/acled_data/acled-version-5-all-africa-1997-2014dyadicupdate.xlsx"
        acled = pd.read_excel(acled_path)
        data_info['acled'] = {
            'n_rows': len(acled),
            'n_cols': len(acled.columns),
            'columns': acled.columns.tolist(),
            'years': sorted(acled['YEAR'].unique().tolist()),
            'countries': acled['COUNTRY'].nunique()
        }
        print(f"ACLED data loaded: {len(acled)} events")
    except Exception as e:
        data_info['acled'] = {'error': str(e)}
        print(f"Could not load ACLED: {e}")

    # 2. Load World Bank project data
    try:
        projects_path = f"{RAW_DATA_PATH}/wb_data/projects.csv"
        projects = pd.read_csv(projects_path)
        data_info['wb_projects'] = {
            'n_rows': len(projects),
            'columns': projects.columns.tolist()
        }
        print(f"WB projects loaded: {len(projects)} rows")
    except Exception as e:
        data_info['wb_projects'] = {'error': str(e)}

    # 3. Load locations data
    try:
        locations_path = f"{RAW_DATA_PATH}/wb_data/locations.csv"
        locations = pd.read_csv(locations_path)
        data_info['wb_locations'] = {
            'n_rows': len(locations),
            'columns': locations.columns.tolist()
        }
        print(f"WB locations loaded: {len(locations)} rows")
    except Exception as e:
        data_info['wb_locations'] = {'error': str(e)}

    # 4. Load team leader CV data
    try:
        ttl_path = f"{RAW_DATA_PATH}/limodio_data/ttl_cv_data.dta"
        ttl = pd.read_stata(ttl_path)
        data_info['ttl_cv'] = {
            'n_rows': len(ttl),
            'columns': ttl.columns.tolist()
        }
        print(f"TTL CV data loaded: {len(ttl)} leaders")
    except Exception as e:
        data_info['ttl_cv'] = {'error': str(e)}

    # 5. Load project database
    try:
        projdb_path = f"{RAW_DATA_PATH}/limodio_data/project_database_original.dta"
        projdb = pd.read_stata(projdb_path)
        data_info['project_db'] = {
            'n_rows': len(projdb),
            'columns': projdb.columns.tolist()[:20]  # First 20 columns
        }
        print(f"Project database loaded: {len(projdb)} projects")
    except Exception as e:
        data_info['project_db'] = {'error': str(e)}

    # 6. Load grid structure
    try:
        grid_path = f"{RAW_DATA_PATH}/africa_1deggrid_buffer_intersection.csv"
        grid = pd.read_csv(grid_path)
        n_cells = grid['ID'].nunique()
        data_info['grid'] = {
            'n_cells': n_cells,
            'columns': grid.columns.tolist()
        }
        print(f"Grid structure loaded: {n_cells} unique cells")
    except Exception as e:
        data_info['grid'] = {'error': str(e)}

    return data_info


def generate_specification_documentation():
    """
    Document what specifications WOULD be run if data were available.
    Based on analysis of the Stata do files.
    """

    specs = []

    # ========================================================================
    # TABLE 2: BASELINE RESULTS
    # ========================================================================

    # Panel A: OLS with Fixed Effects
    specs.append({
        'spec_id': 'baseline',
        'spec_tree_path': 'methods/panel_fixed_effects.md',
        'description': 'OLS with grid cell + year FE, clustered by grid cell',
        'stata_command': 'reghdfe i_conflict any_aid mean_qoutcome if yr>2 & ccode!=., cluster(ID) absorb(ID yr)',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome',
        'fixed_effects': 'ID + yr (grid cell + year)',
        'controls': 'any_aid',
        'cluster_var': 'ID (grid cell)',
        'model_type': 'OLS/FE',
        'table_reference': 'Table 2, Panel A, Column 1',
        'data_missing': True
    })

    specs.append({
        'spec_id': 'panel/controls/sector',
        'spec_tree_path': 'methods/panel_fixed_effects.md#control-sets',
        'description': 'OLS with FE + sector controls',
        'stata_command': 'reghdfe i_conflict any_aid mean_qoutcome sect1d_* if yr>2 & ccode!=., cluster(ID) absorb(ID yr)',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome',
        'fixed_effects': 'ID + yr',
        'controls': 'any_aid, sect1d_* (75 sector dummies)',
        'cluster_var': 'ID',
        'model_type': 'OLS/FE',
        'table_reference': 'Table 2, Panel A, Column 2',
        'data_missing': True
    })

    specs.append({
        'spec_id': 'panel/fe/twoway_country',
        'spec_tree_path': 'methods/panel_fixed_effects.md#fixed-effects-structure',
        'description': 'OLS with grid cell + year-country FE',
        'stata_command': 'reghdfe i_conflict any_aid mean_qoutcome if yr>2 & ccode!=., cluster(ID) absorb(ID yr#ccode)',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome',
        'fixed_effects': 'ID + yr#ccode (grid cell + year x country)',
        'controls': 'any_aid',
        'cluster_var': 'ID',
        'model_type': 'OLS/FE',
        'table_reference': 'Table 2, Panel A, Column 3',
        'data_missing': True
    })

    specs.append({
        'spec_id': 'panel/controls/sector_fe_twoway',
        'spec_tree_path': 'methods/panel_fixed_effects.md#control-sets',
        'description': 'OLS with year-country FE + sector controls',
        'stata_command': 'reghdfe i_conflict any_aid mean_qoutcome sect1d_* if yr>2 & ccode!=., cluster(ID) absorb(ID yr#ccode)',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome',
        'fixed_effects': 'ID + yr#ccode',
        'controls': 'any_aid, sect1d_*',
        'cluster_var': 'ID',
        'model_type': 'OLS/FE',
        'table_reference': 'Table 2, Panel A, Column 4',
        'data_missing': True
    })

    specs.append({
        'spec_id': 'panel/sample/weighted',
        'spec_tree_path': 'methods/panel_fixed_effects.md#sample-restrictions',
        'description': 'OLS weighted by total projects in period',
        'stata_command': 'reghdfe i_conflict any_aid mean_qoutcome sect1d_* if yr>2 & ccode!=. [aweight = tot_proj_period], cluster(ID) absorb(ID yr#ccode)',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome',
        'fixed_effects': 'ID + yr#ccode',
        'controls': 'any_aid, sect1d_*',
        'cluster_var': 'ID',
        'model_type': 'OLS/FE weighted',
        'table_reference': 'Table 2, Panel A, Column 5',
        'data_missing': True
    })

    # Panel B: IV with Leader Fixed Effects
    specs.append({
        'spec_id': 'iv/method/liml',
        'spec_tree_path': 'methods/instrumental_variables.md#estimation-method',
        'description': 'IV-LIML using team leader FE as instruments for project quality',
        'stata_command': 'ivreghdfe i_conflict any_aid (mean_qoutcome = leadxx_1-leadxx_845) if yr>2 & ccode!=., cluster(ID) absorb(ID yr) liml',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome (instrumented)',
        'instruments': 'leadxx_1-leadxx_845 (845 team leader indicators)',
        'fixed_effects': 'ID + yr',
        'controls': 'any_aid',
        'cluster_var': 'ID',
        'model_type': 'IV-LIML',
        'table_reference': 'Table 2, Panel B, Column 1',
        'data_missing': True
    })

    specs.append({
        'spec_id': 'iv/controls/sector_liml',
        'spec_tree_path': 'methods/instrumental_variables.md#control-sets',
        'description': 'IV-LIML with sector controls',
        'stata_command': 'ivreghdfe i_conflict any_aid (mean_qoutcome = leadxx_1-leadxx_845) sect1d_* if yr>2 & ccode!=., cluster(ID) absorb(ID yr) liml',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome (instrumented)',
        'instruments': 'leadxx_1-leadxx_845',
        'fixed_effects': 'ID + yr',
        'controls': 'any_aid, sect1d_*',
        'cluster_var': 'ID',
        'model_type': 'IV-LIML',
        'table_reference': 'Table 2, Panel B, Column 2',
        'data_missing': True
    })

    specs.append({
        'spec_id': 'iv/fe/twoway_country_liml',
        'spec_tree_path': 'methods/instrumental_variables.md#fixed-effects',
        'description': 'IV-LIML with year-country FE',
        'stata_command': 'ivreghdfe i_conflict any_aid (mean_qoutcome = leadxx_1-leadxx_845) if yr>2 & ccode!=., cluster(ID) absorb(ID yr#ccode) liml',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome (instrumented)',
        'instruments': 'leadxx_1-leadxx_845',
        'fixed_effects': 'ID + yr#ccode',
        'controls': 'any_aid',
        'cluster_var': 'ID',
        'model_type': 'IV-LIML',
        'table_reference': 'Table 2, Panel B, Column 3',
        'data_missing': True
    })

    # Panel C: IV for both aid presence and quality
    specs.append({
        'spec_id': 'iv/instruments/both_endog',
        'spec_tree_path': 'methods/instrumental_variables.md#instrument-sets',
        'description': 'IV-LIML instrumenting both any_aid and mean_qoutcome',
        'stata_command': 'ivreghdfe i_conflict (any_aid mean_qoutcome = iv_2 leadxx_1-leadxx_845) if yr>2 & ccode!=., cluster(ID) absorb(ID yr) liml',
        'outcome_var': 'i_conflict',
        'treatment_var': 'any_aid, mean_qoutcome (both instrumented)',
        'instruments': 'iv_2 (external aid exposure), leadxx_1-leadxx_845',
        'fixed_effects': 'ID + yr',
        'controls': 'none',
        'cluster_var': 'ID',
        'model_type': 'IV-LIML',
        'table_reference': 'Table 2, Panel C, Column 1',
        'data_missing': True
    })

    # ========================================================================
    # ALTERNATIVE OUTCOMES (Tables/Figures)
    # ========================================================================

    for outcome, desc in [
        ('i_violent_conflict', 'Violent conflict indicator'),
        ('i_conflictf', 'Conflict with fatalities'),
        ('i_greater1_d', 'Multiple conflicts (>1 event)'),
        ('i_battles', 'Battles indicator'),
        ('i_violence_against_civ', 'Violence against civilians'),
        ('i_riots_protest', 'Riots or protests'),
        ('i_civ', 'Civil conflict indicator'),
        ('i_nonciv', 'Non-civil conflict indicator')
    ]:
        specs.append({
            'spec_id': f'panel/outcome/{outcome}',
            'spec_tree_path': 'methods/panel_fixed_effects.md',
            'description': f'OLS with FE, outcome = {desc}',
            'stata_command': f'reghdfe {outcome} any_aid mean_qoutcome sect1d_* if yr>2 & ccode!=., cluster(ID) absorb(ID yr#ccode)',
            'outcome_var': outcome,
            'treatment_var': 'mean_qoutcome',
            'fixed_effects': 'ID + yr#ccode',
            'controls': 'any_aid, sect1d_*',
            'cluster_var': 'ID',
            'model_type': 'OLS/FE',
            'table_reference': 'Figure 8 and various tables',
            'data_missing': True
        })

    # ========================================================================
    # ROBUSTNESS CHECKS
    # ========================================================================

    # Different clustering
    specs.append({
        'spec_id': 'robust/cluster/country',
        'spec_tree_path': 'robustness/clustering_variations.md',
        'description': 'Baseline clustered at country level',
        'stata_command': 'reghdfe i_conflict any_aid mean_qoutcome sect1d_* if yr>2 & ccode!=., cluster(ccode) absorb(ID yr#ccode)',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome',
        'fixed_effects': 'ID + yr#ccode',
        'controls': 'any_aid, sect1d_*',
        'cluster_var': 'ccode (country)',
        'model_type': 'OLS/FE',
        'table_reference': 'Table A7',
        'data_missing': True
    })

    # Geographic controls
    for control in ['diamond', 'petrol', 'agsuit', 'split']:
        specs.append({
            'spec_id': f'robust/controls/geo_{control}',
            'spec_tree_path': 'robustness/leave_one_out.md',
            'description': f'IV-LIML with {control} x year interaction',
            'stata_command': f'ivreghdfe i_conflict any_aid (mean_qoutcome = leadxx_1-leadxx_845) sect1d_* if yr>2 & ccode!=., cluster(ID) absorb(ID yr#ccode yr#{control}) liml',
            'outcome_var': 'i_conflict',
            'treatment_var': 'mean_qoutcome (instrumented)',
            'instruments': 'leadxx_1-leadxx_845',
            'fixed_effects': f'ID + yr#ccode + yr#{control}',
            'controls': 'any_aid, sect1d_*',
            'cluster_var': 'ID',
            'model_type': 'IV-LIML',
            'table_reference': 'Table A4',
            'data_missing': True
        })

    # Lagged conflict controls
    specs.append({
        'spec_id': 'robust/controls/lagged_conflict',
        'spec_tree_path': 'robustness/functional_form.md',
        'description': 'IV-LIML with lagged conflict control',
        'stata_command': 'ivreghdfe i_conflict any_aid (mean_qoutcome = leadxx_1-leadxx_845) l.i_conflict sect1d_* if yr>2 & ccode!=., cluster(ID) absorb(ID yr#ccode) liml',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome (instrumented)',
        'instruments': 'leadxx_1-leadxx_845',
        'fixed_effects': 'ID + yr#ccode',
        'controls': 'any_aid, sect1d_*, l.i_conflict',
        'cluster_var': 'ID',
        'model_type': 'IV-LIML',
        'table_reference': 'Table A4, Column 7',
        'data_missing': True
    })

    # Disbursement controls
    specs.append({
        'spec_id': 'robust/controls/disbursement',
        'spec_tree_path': 'robustness/single_covariate.md',
        'description': 'IV-LIML controlling for log disbursements',
        'stata_command': 'ivreghdfe i_conflict any_aid (mean_qoutcome = leadxx_1-leadxx_845) ln_tot_disburs if yr>2 & ccode!=., cluster(ID) absorb(ID yr) liml',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome (instrumented)',
        'instruments': 'leadxx_1-leadxx_845',
        'fixed_effects': 'ID + yr',
        'controls': 'any_aid, ln_tot_disburs',
        'cluster_var': 'ID',
        'model_type': 'IV-LIML',
        'table_reference': 'Table A5',
        'data_missing': True
    })

    # 2SLS vs LIML comparison
    specs.append({
        'spec_id': 'iv/method/2sls',
        'spec_tree_path': 'methods/instrumental_variables.md#estimation-method',
        'description': 'IV-2SLS for comparison with LIML',
        'stata_command': 'ivreghdfe i_conflict any_aid (mean_qoutcome = leadxx_1-leadxx_845) sect1d_* if yr>2 & ccode!=., cluster(ID) absorb(ID yr#ccode)',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome (instrumented)',
        'instruments': 'leadxx_1-leadxx_845',
        'fixed_effects': 'ID + yr#ccode',
        'controls': 'any_aid, sect1d_*',
        'cluster_var': 'ID',
        'model_type': 'IV-2SLS',
        'table_reference': 'Table A3',
        'data_missing': True
    })

    # Different IV specification
    specs.append({
        'spec_id': 'iv/instruments/alt_iv',
        'spec_tree_path': 'methods/instrumental_variables.md#instrument-sets',
        'description': 'IV using within-Africa aid exposure instrument',
        'stata_command': 'ivreghdfe i_conflict (any_aid mean_qoutcome = iv_1 leadxx_1-leadxx_845) if yr>2 & ccode!=., cluster(ID) absorb(ID yr) liml',
        'outcome_var': 'i_conflict',
        'treatment_var': 'any_aid, mean_qoutcome',
        'instruments': 'iv_1 (within-Africa aid exposure), leadxx_1-leadxx_845',
        'fixed_effects': 'ID + yr',
        'controls': 'none',
        'cluster_var': 'ID',
        'model_type': 'IV-LIML',
        'table_reference': 'Table A2',
        'data_missing': True
    })

    # Exclude development policy lending
    specs.append({
        'spec_id': 'robust/sample/no_dpl',
        'spec_tree_path': 'robustness/sample_restrictions.md',
        'description': 'Exclude development policy lending projects',
        'stata_command': 'reghdfe i_conflict any_aid mean_qoutcome sect1d_* if yr>2 & ccode!=., cluster(ID) absorb(ID yr#ccode) [using NO_DPF data]',
        'outcome_var': 'i_conflict',
        'treatment_var': 'mean_qoutcome',
        'fixed_effects': 'ID + yr#ccode',
        'controls': 'any_aid, sect1d_*',
        'cluster_var': 'ID',
        'model_type': 'OLS/FE',
        'table_reference': 'Table A6',
        'data_missing': True
    })

    return specs


def create_results_csv(specs):
    """Create the specification results CSV (with missing data flags)."""

    results = []
    for spec in specs:
        results.append({
            'paper_id': PAPER_ID,
            'journal': JOURNAL,
            'paper_title': PAPER_TITLE,
            'spec_id': spec['spec_id'],
            'spec_tree_path': spec['spec_tree_path'],
            'outcome_var': spec['outcome_var'],
            'treatment_var': spec['treatment_var'],
            'coefficient': np.nan,  # Cannot compute
            'std_error': np.nan,
            't_stat': np.nan,
            'p_value': np.nan,
            'ci_lower': np.nan,
            'ci_upper': np.nan,
            'n_obs': np.nan,
            'r_squared': np.nan,
            'coefficient_vector_json': json.dumps({'error': 'Data not available', 'stata_command': spec['stata_command']}),
            'sample_desc': spec.get('description', ''),
            'fixed_effects': spec.get('fixed_effects', ''),
            'controls_desc': spec.get('controls', ''),
            'cluster_var': spec.get('cluster_var', ''),
            'model_type': spec.get('model_type', ''),
            'estimation_script': f'scripts/paper_analyses/{PAPER_ID}.py',
            'data_missing': True,
            'table_reference': spec.get('table_reference', '')
        })

    df = pd.DataFrame(results)
    output_file = f"{OUTPUT_PATH}/specification_results.csv"
    df.to_csv(output_file, index=False)
    print(f"Results saved to: {output_file}")
    return df


def create_summary_report(specs, data_info):
    """Create the SPECIFICATION_SEARCH.md summary report."""

    report = f"""# Specification Search: {PAPER_TITLE}

## Paper Overview
- **Paper ID**: {PAPER_ID}
- **Journal**: {JOURNAL}
- **Author**: Jacob Moscona
- **Topic**: Effect of World Bank aid project management quality on conflict in Africa
- **Hypothesis**: Better-managed aid projects (higher IEG outcome scores) reduce local conflict
- **Method**: Panel Fixed Effects with Instrumental Variables (Leader FE as instruments)
- **Data**: World Bank project locations + ACLED conflict events, grid-cell panel 1995-2014

## Classification
- **Method Type**: `panel_fixed_effects` with `instrumental_variables`
- **Primary Spec Tree Path**: methods/instrumental_variables.md
- **Secondary Path**: methods/panel_fixed_effects.md

## Data Status

**CRITICAL**: The processed analysis datasets are NOT included in the replication package.
The `Data/Analysis/` directory is empty. The analysis requires intermediate datasets generated
by Stata scripts using spatial GIS operations (shp2dta, geoinpoly) that cannot be replicated
in Python without extensive preprocessing.

### Required But Missing Datasets
- `wb_project_with_conflict_F.dta` - Main analysis dataset
- `wb_project_grid_cell_F.dta` - World Bank projects by grid cell
- `conflict_panel_grid_F.dta` - ACLED conflicts by grid cell
- `grid_cells_year.dta` - Panel structure
- Various leader value-added merge files

### Available Raw Data
| Dataset | Records | Description |
|---------|---------|-------------|
| ACLED conflict | {data_info.get('acled', {}).get('n_rows', 'N/A')} events | Armed conflict events 1997-2014 |
| WB Projects | {data_info.get('wb_projects', {}).get('n_rows', 'N/A')} rows | World Bank project data |
| WB Locations | {data_info.get('wb_locations', {}).get('n_rows', 'N/A')} rows | Project geo-locations |
| Team Leader CVs | {data_info.get('ttl_cv', {}).get('n_rows', 'N/A')} | Leader characteristics |
| Project Database | {data_info.get('project_db', {}).get('n_rows', 'N/A')} | IEG evaluations |
| Grid Cells | {data_info.get('grid', {}).get('n_cells', 'N/A')} | 1-degree cells |

## Summary Statistics

| Metric | Value |
|--------|-------|
| Total specifications documented | {len(specs)} |
| Specifications runnable | 0 |
| Data available | No (processing required) |

## Specifications Documented

| Category | N | Description |
|----------|---|-------------|
| Baseline | 1 | Main OLS result (Table 2, Panel A, Col 1) |
| Panel FE variations | 4 | Different FE and control combinations |
| IV-LIML specifications | 5 | Leader FE as instruments |
| Alternative outcomes | 8 | Different conflict measures |
| Robustness checks | 8 | Clustering, controls, samples |
| **Total** | **{len(specs)}** | |

## Key Findings (from paper)

Based on the Stata do files and paper description:

1. **Baseline Result**: Better project management (higher `mean_qoutcome`) reduces conflict probability
2. **IV estimates**: Using team leader fixed effects as instruments confirms the negative relationship
3. **Heterogeneity**: Effect is stronger for violent conflicts, and varies by project phase
4. **Robustness**: Results hold across different FE structures, clustering, and sample restrictions

## Critical Caveats

1. **CANNOT REPLICATE**: Analysis datasets are not included in replication package
2. **Spatial operations required**: Data processing requires Stata's spatial commands or equivalent GIS tools
3. **Many instruments**: 845 team leader indicators used as instruments - many-instrument bias possible
4. **Weak identification concern**: With many instruments, LIML is used instead of 2SLS

## Method Classification Notes

This paper uses a **hybrid approach**:
1. **Panel Fixed Effects** for controlling unobserved heterogeneity
2. **Instrumental Variables** for addressing endogeneity of project quality
   - Instruments: Team leader fixed effects (845 indicators)
   - Estimator: LIML (to address many-instrument bias)
3. **Sample restrictions** based on year (>1997) and non-missing country codes

The identification argument: Project quality is endogenous (better projects may be assigned to less conflict-prone areas). Team leaders are quasi-randomly assigned across projects, so leader fixed effects predict project quality but are unrelated to local conflict conditions.

## Files Generated

- `specification_results.csv` (documented specifications, no estimates due to missing data)
- `scripts/paper_analyses/{PAPER_ID}.py` (this script)
- `SPECIFICATION_SEARCH.md` (this report)

## Recommendations

To complete this analysis:

1. **Option A**: Run the Stata do files (01-04) to generate the processed datasets, then use Python for specification search
2. **Option B**: Implement spatial joining in Python using geopandas:
   - Create 1-degree grid cells from shapefile
   - Spatially join World Bank locations to grid cells
   - Spatially join ACLED events to grid cells
   - Merge all data and run regressions using pyfixest

## References

- Stata analysis files: `Code/08 analysis_main.do`, `Code/10 analysis_appendix.do`
- Data cleaning files: `Code/01-04 *.do`
"""

    output_file = f"{OUTPUT_PATH}/SPECIFICATION_SEARCH.md"
    with open(output_file, 'w') as f:
        f.write(report)
    print(f"Report saved to: {output_file}")


def update_tracking_status():
    """Update the tracking status file."""
    status_file = f"{BASE_PATH}/data/tracking/spec_search_status.json"

    try:
        with open(status_file, 'r') as f:
            status = json.load(f)
    except FileNotFoundError:
        status = {'packages_with_data': []}

    # Find or add entry
    entry_found = False
    for pkg in status.get('packages_with_data', []):
        if pkg['id'] == PAPER_ID:
            pkg['status'] = 'data_missing'
            pkg['note'] = 'Analysis datasets not included; raw data requires Stata/GIS processing'
            entry_found = True
            break

    if not entry_found:
        status.setdefault('packages_with_data', []).append({
            'id': PAPER_ID,
            'title': 'The Management of Aid and Conflict in Africa',
            'journal': JOURNAL,
            'status': 'data_missing',
            'note': 'Analysis datasets not included; raw data requires Stata/GIS processing'
        })

    with open(status_file, 'w') as f:
        json.dump(status, f, indent=2)

    print(f"Tracking status updated: {status_file}")


def main():
    print("=" * 70)
    print(f"Specification Search: {PAPER_ID}")
    print(f"Paper: {PAPER_TITLE}")
    print("=" * 70)

    # Load available data
    print("\n1. Loading available data...")
    data_info = load_available_data()

    # Document specifications
    print("\n2. Documenting specifications from Stata code...")
    specs = generate_specification_documentation()
    print(f"   {len(specs)} specifications documented")

    # Create results CSV
    print("\n3. Creating specification results CSV...")
    df = create_results_csv(specs)

    # Create summary report
    print("\n4. Creating summary report...")
    create_summary_report(specs, data_info)

    # Update tracking
    print("\n5. Updating tracking status...")
    update_tracking_status()

    print("\n" + "=" * 70)
    print("COMPLETE")
    print("=" * 70)
    print("\nNOTE: Specifications documented but NOT executed due to missing data.")
    print("The replication package does not include processed analysis datasets.")
    print("Run Stata cleaning scripts (01-04) first, or implement spatial joins in Python.")


if __name__ == "__main__":
    main()
